export enum ClsNamespaces {
  "MODULE_NAME" = "MODULE_NAME",
  "SUB_MODULE_NAME" = "SUB_MODULE_NAME",
  "MODULE_DEPTH_NAME" = "MODULE_DEPTH_NAME",
  "EVENT_NAME" = "EVENT_NAME",
  "PARALLELIZE" = "PARALLELIZE",
  "BLOCK_CONFIRMATION_NUMBER" = "BLOCK_CONFIRMATION_NUMBER",
  "IGNITION_NETWORK_ID" = "IGNITION_NETWORK_ID",
  "IGNITION_RPC_PROVIDER" = "IGNITION_RPC_PROVIDER",
  "IGNITION_NETWORK_NAME" = "IGNITION_NETWORK_NAME",
}
