export enum ClsNamespaces {
  "MODULE_NAME" = "MODULE_NAME",
  "SUB_MODULE_NAME" = "SUB_MODULE_NAME",
  "MODULE_DEPTH_NAME" = "MODULE_DEPTH_NAME",
  "EVENT_NAME" = "EVENT_NAME",
  "PARALLELIZE" = "PARALLELIZE",
}
